---

- name: ensure logrotate package
  package:
    name: logrotate
    state: present

- name: ensure default configuration
  template:
    src: logrotate.conf.j2
    dest: /etc/logrotate.conf
    mode: '0644'
    owner: root

- name: setup additional logrotate.d stanza's
  template:
    src: logrotate.d.j2
    dest: "/etc/logrotate.d/{{ item.name }}"
    mode: '0644'
    owner: root
  with_items: "{{ logrotate_files }}"
