---
# tasks file for coffeesprout.rsyslog

- name: ensure packages are installed
  package:
    name: "{{ item }}" 
    state: present
  with_items:
  - "{{ rsyslog_packages }}"

- name: optionally ensure the CA file is loaded
  get_url:
    dest: "{{ rsyslog_ca_file }}" 
    url: "{{ rsyslog_ca_url }}" 
    checksum: "{{ rsyslog_ca_hash }}" 
    owner: root
    mode: '0400'
  when: "rsyslog_ca_url is defined"

- name: setup additional rsyslog.d stanza's
  template:
    src: rsyslog.d.j2
    dest: "/etc/rsyslog.d/{{ item.name }}.conf"
    mode: '0644'
    owner: root
  with_items: "{{ rsyslogd_files }}"

#Setup logrotate

- include_tasks:
    file: logrotate.yml
    apply:
      tags:
      - logrotate
