---
# tasks file for syslog
- name: ensure packages are installed
  package: name="{{ item }}" state=present
  with_items: "{{ rsyslog_packages }}"
  notify: reload rsyslog

- name: optionally ensure the CA file is loaded
  get_url: dest="{{ rsyslog_ca_file }}" url="{{ rsyslog_ca_url }}" checksum="{{ rsyslog_ca_hash }}" owner=root mode=0400
  when: rsyslog_ca_url is defined

- name: ensure rsyslog.conf is updated
  template: dest=/etc/rsyslog.conf src=rsyslog-{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.conf  backup=yes
  with_items: "{{ rsyslog_conf }}"
  notify: reload rsyslog
